//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCUBooking.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DCUModelContainer : DbContext
    {
        public DCUModelContainer()
            : base("name=DCUModelContainer")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
        }

        public virtual DbSet<Dic_Business> Dic_Business { get; set; }
        public virtual DbSet<Dic_CustomSegment> Dic_CustomSegment { get; set; }
        public virtual DbSet<Dic_DCUUser> Dic_DCUUser { get; set; }
        public virtual DbSet<Dic_Horizontal> Dic_Horizontal { get; set; }
        public virtual DbSet<Dic_Industry> Dic_Industry { get; set; }
        public virtual DbSet<Dic_Language> Dic_Language { get; set; }
        public virtual DbSet<Dic_OpportunityType> Dic_OpportunityType { get; set; }
        public virtual DbSet<Dic_RequestGroup> Dic_RequestGroup { get; set; }
        public virtual DbSet<Dic_SaleStage> Dic_SaleStage { get; set; }
        public virtual DbSet<Dic_Technology> Dic_Technology { get; set; }
        public virtual DbSet<Set_Holiday> Set_Holiday { get; set; }
        public virtual DbSet<Set_ShowTime> Set_ShowTime { get; set; }
        public virtual DbSet<Sys_MailTask> Sys_MailTask { get; set; }
        public virtual DbSet<Sys_OperationLogs> Sys_OperationLogs { get; set; }
        public virtual DbSet<Sys_RoomsReservedInfo> Sys_RoomsReservedInfo { get; set; }
        public virtual DbSet<PlaceRequestRecords> PlaceRequestRecords { get; set; }
    }
}
