//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCUBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Set_ShowTime
    {
        public int ID { get; set; }
        public byte Week { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public byte SettingType { get; set; }
        public bool IsRegular { get; set; }
        public Nullable<System.DateTime> SpecifiedDate { get; set; }
        public Nullable<bool> Available { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Remarks { get; set; }
    }
}
