//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCUBooking.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web.Mvc;

    public partial class Set_Holiday
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long ID { get; set; }

        [Required]
        [Remote("CheckDateExist", "Set_Holiday", ErrorMessage = "The specified date already exists.")]
        public DateTime Date { get; set; }

        [Required]
        [StringLength(20)]
        public string HolidayType { get; set; }

        public bool IsWorkDay { get; set; }

        [StringLength(256)]
        public string Remarks { get; set; }

        public string DateString
        {
            get
            {
                return Date.ToString("yyyy/MM/dd");
            }
        }
    }
}
