//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCUBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_RoomsReservedInfo
    {
        public long ID { get; set; }
        public long RecordID { get; set; }
        public byte PlaceID { get; set; }
        public System.DateTime VisitDate { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public System.DateTime LockedTime { get; set; }
        public Nullable<int> TourType { get; set; }
        public int SourceTour { get; set; }
    }
}
