//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCUBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlaceRequestRecords
    {
        public long ID { get; set; }
        public System.DateTime VisitStartTime { get; set; }
        public System.DateTime VisitEndTime { get; set; }
        public string RequesterName { get; set; }
        public string RequesterOnbehalfof { get; set; }
        public Nullable<int> RequestGroupID { get; set; }
        public Nullable<int> RequestSubGroupID { get; set; }
        public string RequesterFunctionTeam { get; set; }
        public Nullable<int> RequesterBusinessID { get; set; }
        public string VisitorOrganizationName { get; set; }
        public Nullable<long> VisitorOrganizationSize { get; set; }
        public Nullable<int> VisitorIndustryID { get; set; }
        public Nullable<long> VisitorGroupSize { get; set; }
        public byte VisitorLanguageID { get; set; }
        public byte RequestType { get; set; }
        public byte Status { get; set; }
        public string BusinessPurpose { get; set; }
        public string BusinessImpact { get; set; }
        public string OPPID { get; set; }
        public Nullable<System.DateTime> ExpectStartTime { get; set; }
        public Nullable<System.DateTime> ExpectEndTime { get; set; }
        public string InterestTopic { get; set; }
        public string CompanyBackground { get; set; }
        public Nullable<System.DateTime> RequestTime { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedTime { get; set; }
        public string UserInfoFile { get; set; }
    }
}
