//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCUBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_OperationLogs
    {
        public long ID { get; set; }
        public int BusinessType { get; set; }
        public int OperationType { get; set; }
        public long RecordID { get; set; }
        public string Operator { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string Remarks { get; set; }
    }
}
